(function(){
'use strict';
// Utilidades
const fmtDate=(d)=>{if(!d)return'';const x=(d instanceof Date)?d:new Date(d);const y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),da=String(x.getDate()).padStart(2,'0');return `${y}-${m}-${da}`;};
const todayStr=()=>fmtDate(new Date());
const addMonths=(d,m)=>{const x=new Date(d);const day=x.getDate();x.setMonth(x.getMonth()+m);if(x.getDate()!==day)x.setDate(0);return x;};
const addYears=(d,y)=>{const x=new Date(d);x.setFullYear(x.getFullYear()+y);return x;};
const daysBetween=(a,b)=>Math.floor((new Date(b)-new Date(a))/(1000*60*60*24));
const calcEstado=(fin)=>{const h=todayStr();if(fmtDate(fin)<h)return{k:'vencido',label:'Vencido'};if(fmtDate(fin)===h)return{k:'hoy',label:'Vence hoy'};return{k:'activo',label:'Activo'}};
// DB
let db;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('control-cuentas',1);r.onupgradeneeded=e=>{const d=e.target.result;d.createObjectStore('clientes',{keyPath:'id',autoIncrement:true});d.createObjectStore('movimientos',{keyPath:'id',autoIncrement:true});d.createObjectStore('servicios',{keyPath:'id',autoIncrement:true});};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error);});}
const tx=(s,m='readonly')=>db.transaction(s,m).objectStore(s);
const saveCliente=(o)=>new Promise((r,j)=>{const q=tx('clientes','readwrite').put(o);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});
const delCliente=(id)=>new Promise((r,j)=>{const q=tx('clientes','readwrite').delete(id);q.onsuccess=()=>r(true);q.onerror=()=>j(q.error);});
const allClientes=()=>new Promise((r,j)=>{const q=tx('clientes').getAll();q.onsuccess=()=>r(q.result||[]);q.onerror=()=>j(q.error);});
const addMov=(m)=>{m.fecha=m.fecha||new Date().toISOString();return new Promise((r,j)=>{const q=tx('movimientos','readwrite').add(m);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});};
const allMov=()=>new Promise((r,j)=>{const q=tx('movimientos').getAll();q.onsuccess=()=>r(q.result||[]);q.onerror=()=>j(q.error);});
const saveServicio=(s)=>new Promise((r,j)=>{const q=tx('servicios','readwrite').put(s);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});
const delServicio=(id)=>new Promise((r,j)=>{const q=tx('servicios','readwrite').delete(id);q.onsuccess=()=>r(true);q.onerror=()=>j(q.error);});
const allServicios=()=>new Promise((r,j)=>{const q=tx('servicios').getAll();q.onsuccess=()=>r(q.result||[]);q.onerror=()=>j(q.error);});
const $=(q)=>document.querySelector(q), $$=(q)=>[...document.querySelectorAll(q)];
// Tabs
$$('#tabs button').forEach(b=>b.addEventListener('click',()=>{$$('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.tab;$$('main section').forEach(s=>s.classList.remove('active'));document.getElementById(t).classList.add('active');if(t==='movimientos')renderMovimientos();if(t==='clientes')renderClientes();if(t==='calendario')renderCalendario();}));
// Servicios select
async function refreshServiciosSelect(){const list=await allServicios();const sel=$('#servicio');sel.innerHTML='';list.sort((a,b)=>a.nombre.localeCompare(b.nombre)).forEach(s=>{const o=document.createElement('option');o.value=s.nombre;o.textContent=s.nombre;sel.appendChild(o);});if(sel.options.length===0){const o=document.createElement('option');o.value='SIN ASIGNAR';o.textContent='SIN ASIGNAR';sel.appendChild(o);}}
// Render clientes
async function renderClientes(){const data=await allClientes();const tb=$('#tablaClientes tbody');tb.innerHTML='';const hoy=todayStr();data.sort((a,b)=>new Date(a.fin)-new Date(b.fin));for(const c of data){const est=calcEstado(c.fin);const dias=daysBetween(new Date(),new Date(c.fin));const dstr=(fmtDate(c.fin)===hoy)?'0':(dias>0?dias:`-${Math.abs(dias)}`);const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${c.nombre||''} ${c.apellido||''}</strong><div class="muted">${c.usuarioPlataforma||''}</div></td><td>${c.email||''}</td><td>${c.servicio||''} <span class="muted">${c.plan||''}</span></td><td>${fmtDate(c.inicio)} → ${fmtDate(c.fin)}</td><td>${dstr}</td><td>$ ${Number(c.precio||0).toFixed(2)}</td><td>${est.label}</td>`;tr.addEventListener('click',()=>loadClienteToForm(c));tb.appendChild(tr);}}
// Calendario simple (placeholder)
function renderCalendario(){const el=document.getElementById('gridCal');if(!el)return;el.textContent='(Calendario listo)';}
// Movimientos
async function renderMovimientos(){const data=await allMov();const tb=document.querySelector('#tablaMov tbody');tb.innerHTML='';data.sort((a,b)=>new Date(b.fecha)-new Date(a.fecha));for(const m of data){const tr=document.createElement('tr');tr.innerHTML=`<td>${m.fecha}</td><td>${m.tipo}</td><td>${m.cliente}</td><td>${m.servicio}</td><td>${m.plan}</td><td>${m.monto}</td><td>${m.notas||''}</td>`;tb.appendChild(tr);}}
// Form cliente
function loadClienteToForm(c){$('#clienteId').value=c.id||'';$('#nombre').value=c.nombre||'';$('#apellido').value=c.apellido||'';$('#email').value=c.email||'';$('#servicio').value=c.servicio||'SIN ASIGNAR';$('#plan').value=c.plan||'mensual';$('#precio').value=c.precio||0;$('#estado').value=c.estado||'activo';$('#usuarioPlataforma').value=c.usuarioPlataforma||'';$('#contrasenaVisible').value=c.passPlain||'';$('#notas').value=c.notas||'';$('#inicio').value=fmtDate(c.inicio)||todayStr();$('#fin').value=fmtDate(c.fin)||todayStr();}
if($('#formCliente'))$('#formCliente').addEventListener('submit',async e=>{e.preventDefault();const obj={id:Number($('#clienteId').value)||undefined,nombre:($('#nombre').value||'').trim(),apellido:($('#apellido').value||'').trim(),email:($('#email').value||'').trim(),servicio:$('#servicio').value||'SIN ASIGNAR',plan:$('#plan').value||'mensual',precio:Number($('#precio').value||0),estado:$('#estado').value||'activo',usuarioPlataforma:($('#usuarioPlataforma').value||'').trim(),passPlain:($('#contrasenaVisible').value||'').trim(),notas:($('#notas').value||'').trim(),inicio:$('#inicio').value||todayStr(),fin:$('#fin').value||todayStr()};const isNew=!obj.id;try{const rid=await saveCliente(obj);try{await addMov({tipo:isNew?'ALTA':'EDICIÓN',cliente:(obj.nombre+' '+obj.apellido).trim(),servicio:obj.servicio,plan:obj.plan,monto:obj.precio,notas:isNew?'Alta de cliente':'Edición de datos'});}catch(e){console.warn('mov warn',e);}$('#clienteId').value=rid||obj.id||'';await renderClientes();alert('✔ Guardado');}catch(err){console.error(err);alert('❌ No se pudo guardar: '+(err&&err.message?err.message:err));}});
if($('#btnNuevo'))$('#btnNuevo').addEventListener('click',()=>{$('#formCliente').reset();$('#clienteId').value='';$('#inicio').value=todayStr();$('#fin').value=todayStr();});
if($('#btnEliminar'))$('#btnEliminar').addEventListener('click',async()=>{const id=Number($('#clienteId').value);if(!id)return;await delCliente(id);await addMov({tipo:'BAJA',cliente:'',servicio:'',plan:'',monto:0,notas:'Eliminado'});await renderClientes();});
if($('#btnRenovar'))$('#btnRenovar').addEventListener('click',async()=>{const id=Number($('#clienteId').value);if(!id)return alert('Seleccioná un cliente');const data=await allClientes();const c=data.find(x=>x.id===id);if(!c)return;const base=new Date(c.fin||c.inicio||new Date());c.fin=fmtDate((c.plan==='anual')?addYears(base,1):addMonths(base,1));const np=prompt('Nuevo precio ARS (vacío = mantener):', String(c.precio||''));if(np!==null&&np.trim()!==''){const n=Number(np);if(!Number.isNaN(n))c.precio=n;}await saveCliente(c);await addMov({tipo:'RENOVACIÓN',cliente:c.nombre+' '+c.apellido,servicio:c.servicio,plan:c.plan,monto:c.precio,notas:'Renovación'});await renderClientes();});
// Export
function exportCSV(rows, filename){if(!rows.length){alert('Sin datos');return;}const header=Object.keys(rows[0]).join(',');const body=rows.map(r=>Object.values(r).map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([header+'\n'+body],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();}
function exportXLS(rows, filename){if(!rows.length){alert('Sin datos');return;}const esc=(s)=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const keys=Object.keys(rows[0]);const cols=keys.map(k=>`<Cell><Data ss:Type="String">${esc(k)}</Data></Cell>`).join('');const xmlRows=rows.map(r=>{const cells=keys.map(k=>`<Cell><Data ss:Type="String">${esc(r[k]??'')}</Data></Cell>`).join('');return `<Row>${cells}</Row>`;}).join('');const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Datos"><Table><Row>${cols}</Row>${xmlRows}</Table></Worksheet></Workbook>`;const blob=new Blob([xml],{type:'application/vnd.ms-excel'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();}
function exportTableAsPDF(printHtml, filename){const w=window.open('','_blank');w.document.write(`<html><head><title>${filename}</title><style>body{font-family:Arial}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccc;padding:6px;font-size:12px}th{background:#f3f3f3}</style></head><body>${printHtml}</body></html>`);w.document.close();w.focus();w.print();}
if(document.getElementById('exportCSV'))document.getElementById('exportCSV').addEventListener('click',async()=>{const d=await allClientes();const rows=d.map(c=>({id:c.id,nombre:c.nombre,apellido:c.apellido,email:c.email,servicio:c.servicio,plan:c.plan,precio:c.precio,inicio:fmtDate(c.inicio),fin:fmtDate(c.fin),dias:daysBetween(new Date(),new Date(c.fin)),estado:calcEstado(c.fin).label,notas:c.notas||''}));exportCSV(rows,'clientes.csv');});
if(document.getElementById('exportXLS'))document.getElementById('exportXLS').addEventListener('click',async()=>{const d=await allClientes();const rows=d.map(c=>({id:c.id,nombre:c.nombre,apellido:c.apellido,email:c.email,servicio:c.servicio,plan:c.plan,precio:c.precio,inicio:fmtDate(c.inicio),fin:fmtDate(c.fin),dias:daysBetween(new Date(),new Date(c.fin)),estado:calcEstado(c.fin).label,notas:c.notas||''}));exportXLS(rows,'clientes.xls');});
if(document.getElementById('exportPDF'))document.getElementById('exportPDF').addEventListener('click',async()=>{const d=await allClientes();let html='<h1>Clientes</h1><table><thead><tr><th>ID</th><th>Cliente</th><th>Email</th><th>Servicio</th><th>Plan</th><th>Precio</th><th>Inicio</th><th>Fin</th><th>Días</th><th>Estado</th><th>Notas</th></tr></thead><tbody>';for(const c of d){html+=`<tr><td>${c.id}</td><td>${c.nombre} ${c.apellido}</td><td>${c.email}</td><td>${c.servicio}</td><td>${c.plan}</td><td>${c.precio}</td><td>${fmtDate(c.inicio)}</td><td>${fmtDate(c.fin)}</td><td>${daysBetween(new Date(),new Date(c.fin))}</td><td>${calcEstado(c.fin).label}</td><td>${(c.notas||'').replace(/</g,'&lt;')}</td></tr>`;}html+='</tbody></table>';exportTableAsPDF(html,'clientes.pdf');});
// Copy
function copyVal(inp){const el=document.getElementById(inp);if(!el)return;el.select();el.setSelectionRange(0,99999);document.execCommand('copy');}
if(document.getElementById('copyUsuario'))document.getElementById('copyUsuario').addEventListener('click',()=>copyVal('usuarioPlataforma'));
if(document.getElementById('copyPassVisible'))document.getElementById('copyPassVisible').addEventListener('click',()=>copyVal('contrasenaVisible'));
// Respaldo
if(document.getElementById('btnBackupJSON'))document.getElementById('btnBackupJSON').addEventListener('click',async()=>{const datos={clientes:await allClientes(),servicios:await allServicios(),movimientos:await allMov()};const blob=new Blob([JSON.stringify(datos,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='respaldo_control_cuentas.json';a.click();});
if(document.getElementById('btnImportar'))document.getElementById('btnImportar').addEventListener('click',async()=>{const f=document.getElementById('fileRestore').files[0];if(!f)return alert('Selecciona un .json');const text=await f.text();const data=JSON.parse(text);if(!confirm('Importar respaldo?'))return;if(Array.isArray(data.servicios))for(const s of data.servicios)await saveServicio(s);if(Array.isArray(data.clientes))for(const c of data.clientes)await saveCliente(c);if(Array.isArray(data.movimientos))for(const m of data.movimientos)await addMov(m);await refreshServiciosSelect();await renderClientes();await renderMovimientos();alert('Listo.');});
if(document.getElementById('btnClearDB'))document.getElementById('btnClearDB').addEventListener('click',()=>{indexedDB.deleteDatabase('control-cuentas');alert('Base borrada. Recargá.');});
// Servicios UI
async function renderServicios(){const tb=document.querySelector('#tablaSvc tbody');if(!tb)return;tb.innerHTML='';const list=await allServicios();list.sort((a,b)=>a.nombre.localeCompare(b.nombre));for(const s of list){const tr=document.createElement('tr');tr.innerHTML=`<td>${s.nombre}</td><td>${s.mensual||0}</td><td>${s.anual||0}</td><td>${s.grupo||''}</td>`;tb.appendChild(tr);}}
if(document.getElementById('formServicio'))document.getElementById('formServicio').addEventListener('submit',async e=>{e.preventDefault();const id=Number(document.getElementById('servicioId').value)||undefined;const svc={id,nombre:(document.getElementById('svcNombre').value||'').toUpperCase(),grupo:document.getElementById('svcGrupo').value||'',mensual:Number(document.getElementById('svcMensual').value||0),anual:Number(document.getElementById('svcAnual').value||0)};await saveServicio(svc);await refreshServiciosSelect();await renderServicios();});
if(document.getElementById('svcNuevo'))document.getElementById('svcNuevo').addEventListener('click',()=>{document.getElementById('formServicio').reset();document.getElementById('servicioId').value='';});
// Init
(async function init(){
  try{
    await openDB();
  }catch(e){
    console.error('DB open error', e); alert('Error inicializando base. Recargá la página.'); return;
  }
  if(document.getElementById('inicio'))document.getElementById('inicio').value=todayStr();
  if(document.getElementById('fin'))document.getElementById('fin').value=todayStr();
  // Semilla de servicios si está vacío
  const cur=await allServicios(); if(cur.length===0){ for(const s of ['NETFLIX','SPOTIFY','DISNEY','PRIME']) await saveServicio({nombre:s,grupo:'Streaming',mensual:0,anual:0}); }
  await refreshServiciosSelect(); await renderClientes(); await renderServicios(); await renderMovimientos();
})();})();